var child = [
  { 'dupe': true, 'type': 32, 'name': 'conflict.php', 'dir': 'c0', 'linked': 2, 'url': 'http://10.10.237.237/pictures/conflict.php', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'high_quality.php', 'dir': 'c2', 'linked': 2, 'url': 'http://10.10.237.237/pictures/high_quality.php', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'purchased.php', 'dir': 'c3', 'linked': 2, 'url': 'http://10.10.237.237/pictures/purchased.php', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'recent.php', 'dir': 'c4', 'linked': 2, 'url': 'http://10.10.237.237/pictures/recent.php', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': false, 'type': 32, 'name': 'search.php', 'dir': 'c5', 'linked': 5, 'url': 'http://10.10.237.237/pictures/search.php', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 2, 0, 0, 0 ], 'sig': 0x8dbfd600 },
  { 'dupe': true, 'type': 32, 'name': 'upload.php', 'dir': 'c6', 'linked': 2, 'url': 'http://10.10.237.237/pictures/upload.php', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'view.php', 'dir': 'c7', 'linked': 2, 'url': 'http://10.10.237.237/pictures/view.php', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c9', 'linked': 2, 'url': 'http://10.10.237.237/pictures/?C=N;O=D', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0xdeb6f368 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c10', 'linked': 2, 'url': 'http://10.10.237.237/pictures/?C=N;O=D', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0xdeb6f368 }
];
