var child = [
  { 'dupe': false, 'type': 4, 'name': 'check_pass.php', 'dir': 'c0', 'linked': 2, 'url': 'http://10.10.237.237/users/check_pass.php/', 'fetched': true, 'code': 404, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xc634abbe },
  { 'dupe': false, 'type': 8, 'name': 'sample.php', 'dir': 'c1', 'linked': 2, 'url': 'http://10.10.237.237/users/sample.php', 'fetched': true, 'code': 404, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 1, 2, 0, 0, 0 ], 'sig': 0x62ed59b5 },
  { 'dupe': false, 'type': 16, 'name': 'home.php', 'dir': 'c2', 'linked': 2, 'url': 'http://10.10.237.237/users/home.php', 'fetched': true, 'code': 303, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 1, 0, 0, 0 ], 'sig': 0x1097a49b },
  { 'dupe': false, 'type': 16, 'name': 'login.php', 'dir': 'c3', 'linked': 5, 'url': 'http://10.10.237.237/users/login.php', 'fetched': true, 'code': 200, 'len': 2661, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 3, 2, 1, 1, 0 ], 'sig': 0xc6276095 },
  { 'dupe': false, 'type': 16, 'name': 'logout.php', 'dir': 'c4', 'linked': 2, 'url': 'http://10.10.237.237/users/logout.php', 'fetched': true, 'code': 303, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xc620abbe },
  { 'dupe': false, 'type': 16, 'name': 'register.php', 'dir': 'c5', 'linked': 5, 'url': 'http://10.10.237.237/users/register.php', 'fetched': true, 'code': 200, 'len': 3031, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 3, 5, 1, 1, 0 ], 'sig': 0xfde39403 },
  { 'dupe': true, 'type': 16, 'name': 'similar.php', 'dir': 'c6', 'linked': 2, 'url': 'http://10.10.237.237/users/similar.php', 'fetched': true, 'code': 303, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xc620abbe },
  { 'dupe': true, 'type': 16, 'name': 'view.php', 'dir': 'c7', 'linked': 2, 'url': 'http://10.10.237.237/users/view.php', 'fetched': true, 'code': 303, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xc620abbe },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c8', 'linked': 2, 'url': 'http://10.10.237.237/users/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2351, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 1, 0, 0, 0 ], 'sig': 0x8e218709 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c9', 'linked': 2, 'url': 'http://10.10.237.237/users/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2351, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
